# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: TCP proxy addon
version: "1.0.0"
slug: tcpproxy
description: TCP proxy add-on
url: "https://github.com/gralin/tcp-proxy-ha-addon/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ports:
  5001/tcp: 5001
ports_description:
  5001/tcp: "TCP proxy port"
options:
  message: "Hello world..."
schema:
  message: "str?"
